name: Install Cygwin Action
description: GitHub Action to install Cygwin

inputs:
  platform:
    description: Platform [x86, x86_64]
    required: false
    default: x86_64
  packages:
    description: Packages to install
    required: false
  install-dir:
    # by default, install to C:\cygwin rather than the platform dependent
    # default to make everything simpler
    description: Installation directory
    required: false
    default: C:\cygwin
  check-sig:
    description: Should the setup.ini file signature be checked?
    required: false
    default: true
  site:
    description: Download site URL
    required: false
  add-to-path:
    description: Should Cygwin's bin directory be added to the system PATH?
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - run: |
        $platform = '${{ inputs.platform }}'
        $platform = $platform -replace '^(x64|amd64)$', 'x86_64'
        $platform = $platform -replace '^i686$', 'x86'
        # validate that platform is one of the expected values
        if (($platform -ne 'x86') -and ($platform -ne 'x86_64')) {
          echo "unknown platform $platform"
          exit 1
        }
        Invoke-WebRequest https://cygwin.com/setup-$platform.exe -OutFile C:\setup.exe

        $packages = '${{ inputs.packages }}'
        $pkg_list = $packages.Split('', [System.StringSplitOptions]::RemoveEmptyEntries)
        $pkg_list = $pkg_list | % { $_.Trim() }
        $pkg_list = $pkg_list | % { $_.Trim(',') }

        # default site if not specified
        if (! '${{ inputs.site }}' ) {
          if ($platform -eq 'x86') {
            $site = 'http://mirrors.kernel.org/sourceware/cygwin-archive/20221123'
          } else {
            $site = 'http://mirrors.kernel.org/sourceware/cygwin/'
          }
        } else {
          $site = '${{ inputs.site }}'
        }

        $args = @(
         '-qgnO',
         '-s', $site,
         '-l', 'C:\cygwin-packages',
         '-R', '${{ inputs.install-dir }}'
        )

        if ($pkg_list.Count -gt 0) {
          $args += '-P'
          $args += $pkg_list -Join(',')
        }

        if ('${{ inputs.check-sig }}' -eq $false) {
          $args += '-X'
        }

        if ($platform -eq 'x86') {
          $args += '--allow-unsupported-windows'
        }

        # because setup is a Windows GUI app, make it part of a pipeline to make
        # PowerShell wait for it to exit
        & C:\setup.exe $args | Out-Default
      shell: powershell

    - if: ${{ inputs.add-to-path  == 'true' }}
      run: echo "${{ inputs.install-dir }}\bin" >> $env:GITHUB_PATH
      shell: powershell

    - run: |
        # run login shell to copy skeleton profile files
        ${{ inputs.install-dir }}\bin\bash.exe --login
      shell: powershell

branding:
  color: green
  icon: terminal
